apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: roboshop
  labels:
    app: mongodb
    tier: DB
    project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
      tier: DB
      project: roboshop
  template:
    metadata:
      labels:
        app: mongodb
        tier: DB
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: mongokidambih91/mongo:latest
